[package]
name = "wavetracer-egui"
version = "0.1.0"
edition = "2024"

[dependencies]
eframe = { version = "0.31.1", features = ["wgpu"] }
egui = "0.31.1"
pollster = "0.4.0"
bytemuck = "1"
muscat = { git = "https://github.com/Ledger-Donjon/muscat.git" }
npyz = "0.8.3"
ndarray = "0.16.1"